In [ ]:
!nvidia-smi

Thu May 28 15:42:34 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
x = torch.tensor([1,2,3,4])
print(x)

tensor([1, 2, 3, 4])


In [ ]:
print(x.shape)
print(x.dtype)
print(x.device)

torch.Size([4])
torch.int64
cpu


In [ ]:
a = torch.zeros((2, 3))
b = torch.randn((2, 3))

print(a)
print()
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1.4536, 0.0834, 0.5713],
        [0.0993, 0.3662, 0.2193]])


In [ ]:
tensor = torch.rand(3 , 64 , 64)
print(f"Tensor:\n{tensor}")
print(f"Shape: {tensor.shape}")
print(f"Dtype: {tensor.dtype}")
print(f"Device: {tensor.device}\n")

Tensor:
tensor([[[0.8874, 0.2245, 0.1137,  ..., 0.5426, 0.4542, 0.4690],
         [0.3023, 0.6518, 0.4803,  ..., 0.6619, 0.5736, 0.1566],
         [0.1183, 0.1256, 0.4717,  ..., 0.6697, 0.8587, 0.5396],
         ...,
         [0.6386, 0.7695, 0.5550,  ..., 0.2488, 0.6346, 0.0779],
         [0.1481, 0.9822, 0.3304,  ..., 0.3185, 0.5672, 0.0029],
         [0.4133, 0.7747, 0.3471,  ..., 0.6610, 0.5921, 0.2206]],

        [[0.1911, 0.2670, 0.2415,  ..., 0.6462, 0.4913, 0.7665],
         [0.3303, 0.8244, 0.5714,  ..., 0.4820, 0.1781, 0.0107],
         [0.3050, 0.5073, 0.2782,  ..., 0.7493, 0.1704, 0.8060],
         ...,
         [0.6326, 0.2451, 0.4010,  ..., 0.6450, 0.7720, 0.0923],
         [0.1442, 0.6641, 0.1601,  ..., 0.2964, 0.6299, 0.7516],
         [0.5662, 0.4311, 0.7814,  ..., 0.1158, 0.4625, 0.4265]],

        [[0.9681, 0.6212, 0.4187,  ..., 0.2107, 0.1596, 0.8550],
         [0.1611, 0.6416, 0.4901,  ..., 0.2368, 0.5815, 0.5235],
         [0.6201, 0.7974, 0.8785,  ..., 0.9261, 0.

In [ ]:
import torch
print(torch.cuda.is_available())

True


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [ ]:
tensor_gpu = tensor.to(device)
print(tensor_gpu.device)


cuda:0


In [ ]:
print(tensor_gpu.shape)
print(tensor_gpu.dtype)
print(tensor_gpu.device)

torch.Size([3, 64, 64])
torch.float32
cuda:0


In [ ]:
import time
size = 2000
cpu_a = torch.randn(size, size)
cpu_b = torch.randn(size, size)
start = time.time()
cpu_result = torch.matmul(cpu_a, cpu_b)
cpu_time = time.time() - start
print(f"CPU Time: {cpu_time:.4f} seconds")

CPU Time: 0.1969 seconds


In [ ]:
gpu_a = cpu_a.to(device)
gpu_b = cpu_b.to(device)
torch.cuda.synchronize()
start = time.time()
gpu_result = torch.matmul(gpu_a, gpu_b)
torch.cuda.synchronize()
gpu_time = time.time() - start
print(f"GPU Time: {gpu_time:.4f} seconds")

GPU Time: 0.1600 seconds
